# ---------------------------------------------------------------------------
# Stage 1: parse_corpus
# ---------------------------------------------------------------------------
parse_corpus:
  corpus_root: data/raw/ru-fr_interference
  metadata: data/raw/ru-fr_interference/metadata_RUFR.csv
  rufrcorr: data/raw/ru-fr_interference/RUFRcorr.csv
  output: data/interim/tokens.csv

  debug:
    enable: false
    n_speakers: 4
    n_repetitions: 1