[workspace]
authors = ["jangioj <alessandroangiolillo99@gmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "FINAL_PROJECT"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
snakemake-minimal = ">=9.20.0,<10"
praatio = ">=6.2.2,<7"
pandas = ">=3.0.3,<4"
